### PR TITLE
bower.json main attribute

### PR DESCRIPTION
**Pull request by robertmain**
Added main attribute to bower.json - useful for those of using gulp etc.

### CODE REVIEW

**Comment by AndersDJohnson** [comment]
@robertmain Thanks, but maybe change to `"main": "livestamp.js"` without the unnecessary dot-slash prefix - this matches the `component.json`.

**Comment by robertmain** [comment]
Fixed.

**Comment by AndersDJohnson** [comment]
@mattbradley We should probably create a new tag that's up a patch increment from the current `1.2.2` so Bower is aware of the change. It's probably safe - between master and `1.1.2`, I see only a few changes, mostly to the package json files and adding UMD wrapper.
Not sure if the minified code is in sync with the source though - what are you using to minify? Probably we should start using Grunt or gulp at some point so it's standardized.

**Comment by robertmain** [comment]
If you just provide a bower file most people can minify it themselves using
grunt/gulp, no?

**Comment by AndersDJohnson** [comment]
@robertmain Yes, many people do not use minified builds committed to repos, but I'm hesitant to push a tag with the wrong minified version before confirming with @mattbradley.

**Comment by robertmain** [comment]
Valid point. Fair enough 😊

**Pull request merged**
